name: fastlocation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_mobx: ^2.0.4
  mobx: ^2.0.6+1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.14
  path_provider_android: ^2.0.14
  path_provider_foundation: ^2.0.14
  map_launcher: ^3.5.0
  geocoding: ^3.0.0
  geolocator: ^9.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.5
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_background.jpg
    - assets/images/app_logo.png
